server:
  port: 8081

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: url-service
          uri: lb://url-service  
          predicates:
            - Path=/api/url/**

        - id: user-service
          uri: lb://user-service   
          predicates:
            - Path=/api/user/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  
    register-with-eureka: true
    fetch-registry: true
