server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: url-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/url/**
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/user/**
