server:
  port: 8081

spring:
  application:
    name: url-service

  datasource:
    url: jdbc:postgresql://localhost:5432/syos_db
    username: postgres
    password: bootcamp
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
