server:
  port: 8082

spring:
  application:
    name: url-service

  datasource:
    url: jdbc:postgresql://localhost:5432/url_shortener
    username: postgres
    password: bootcamp
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost  
    prefer-ip-address: true   
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true